use_frameworks!

platform :ios, '15.0'

target 'mottosdkios_Example' do
  pod 'mottosdkios', :path => '../'

  target 'mottosdkios_Tests' do
    inherit! :search_paths

    
  end
  
  
end
#
#pre_install do |installer|
#    def installer.verify_no_static_framework_transitive_dependencies; end
#end
#	
